version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "matplotlib" # Issue #234
      - dependency-name: "scipy"  # section-properties and numba-scipy limit
      - dependency-name: "numpy"  # numba limited
      - dependency-name: "section-properties" # beams needs to be updated
      - dependency-name: "neutronics-material-maker" # incompatible upgrade path
      - dependency-name: "nlopt"  # numpy limited
