[tool.black]
line-length = 89
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | _build
  | buck-out
  | build
  | dist
  | mirapy
  | examples/meshing
)/
'''

[tool.coverage.report]
"exclude_lines" = [
  "if __name__ == .__main__.:"
]
"omit" = [
  "BLUEPRINT/_version.py"
]

[tool.isort]
line_length = 89
profile = "black"
skip_gitignore = true
known_first_party = ["BLUEPRINT", "bluemira"]
force_to_top = ["freecad"]

[tool.pytest.ini_options]
markers = [
    "longrun",
    "reactor",
    "private"
]
addopts = "--html=report.html --self-contained-html --strict-markers"
